# General Dataset and Run Settings
model_type: "decision_tree"  # "decision_tree" or "random_forest"
dataset_path: "/home/yagnihotri/datasets/deepcorr_original_dataset"  # Path to the DeepCorr dataset
run_folder_path: "/home/yagnihotri/projects/corr/lightcorr"  # Path to the folder where the run folder will be created
train_ratio: 0.8  # Training set ratio
flow_size: 300  # Flow size
negative_samples: 1  # Number of negative samples
load_all_data: true  # If true, load all data; otherwise, only load flows with minimum specified packets

# Hyperparameter Search Settings
hyperparameter_search:
  type: "grid_search"  # Type of hyperparameter search ("none", "grid_search", "random_search")
  search_verbosity: 2  # Verbosity level for hyperparameter search
  cross_validation_folds: 5  # Number of folds for cross-validation

  # Parameter grid file path for Grid and Random Search
  param_grid_path: "/home/yagnihotri/projects/corr/lightcorr/hyperparameter_grids/dt/extensive_grid.yaml"  # Path to JSON/YAML file containing the grid of hyperparameters to explore

  # Parameters for Grid Search
  grid_search:
    # Add grid search specific parameters here if needed

  # Parameters for Random Search
  random_search:
    n_iter: 10  # Number of parameter settings sampled for random search

# Decision Tree Parameters
decision_tree:
  criterion: "gini"  # Function to measure the quality of a split ("gini", "log_loss", "entropy")
  splitter: "best"  # Strategy to choose the split at each node ("best", "random")
  max_depth: null  # Maximum depth of the tree (null for unlimited)
  min_samples_split: 2  # Minimum number of samples required to split an internal node
  min_samples_leaf: 1  # Minimum number of samples required to be at a leaf node
  min_weight_fraction_leaf: 0.0  # Minimum weighted fraction of the sum total of weights required at a leaf node
  max_features: null  # Number of features to consider for the best split (integer, float, "sqrt", "log2", "auto")
  random_state: null  # Controls the randomness of the estimator
  max_leaf_nodes: null  # Maximum number of leaf nodes (null for unlimited)
  min_impurity_decrease: 0.0  # A node will be split if the decrease in impurity is greater than this value
  class_weight: null  # Weights associated with classes in the form {class_label: weight}
  ccp_alpha: 0.0  # Complexity parameter used for Minimal Cost-Complexity Pruning

# Random Forest Parameters (placeholders, fill as needed) TO BE COMPLETED
random_forest:
  n_estimators: 100  # Number of trees in the forest
  max_depth: null  # Maximum depth of each tree
  max_features: "auto"  # Number of features to consider for the best split
  # ... additional parameters as needed ...