#####################Dataset loading, splitting and generating settings#####################
load_pregenerated_dataset: True  # If true, load the dataset; otherwise, generate the dataset
pregenerated_dataset_path: "/home/yogeshwar/datasets/deepcorr_pregen/deepcorr_9008_2252"  # Path to the preprocessed dataset
#pregenerated_dataset_path: "/home/yagnihotri/datasets/deepcorr/deepcorr_pregen/deepcorr_9008_2252"  # Path to the preprocessed dataset

# Dataset generation settings
# ONLY USED IF load_pregenerated_dataset IS FALSE
base_dataset_path: "/home/yogeshwar/datasets/deepcorr_original"  # Path to the DeepCorr dataset
#base_dataset_path: "/home/yagnihotri/datasets/deepcorr_original"  # Path to the DeepCorr dataset

train_ratio: 0.8  # Training set ratio
flow_size: 300  # Flow sizes
negative_samples: 1  # Number of negative samples
load_all_data: False  # If true, load all data; otherwise, only load flows with minimum specified packets

# Load dataset fully into memory, if false keeps using memmap arrays
load_dataset_into_memory: False

######################################Run Settings###########################################
model_type: "random_forest"  # "decision_tree" , "random_forest", "xgbClassifier"
run_folder_path: "/home/yogeshwar/master_thesis_corr/lightcorr"  # Path to the folder where the run folder will be created
#run_folder_path: "/home/yagnihotri/projects/corr/lightcorr"

hyperparameter_search_strategy: "none"  # Type of hyperparameter search ("none", "grid_search", "halving_grid_search" "random_search")
selected_hyperparameter_grid: "none"  # Name of the hyperparameter grid to use (see below)

######################################Validation Settings######################################
validation_settings:
  run_validation: true # If true, run validation, otherwise skip validation
  roc_plot_enabled: true  # If true, generate ROC plot
  cross_validation:
    cv: 5  # Number of folds for cross-validation
    n_jobs: -1  # Number of jobs to run in parallel. -1 means using all processors
    verbose: 100  # Verbosity level for cross-validation

######################################Hyperparameter Settings#################################
hyperparameter_search_settings:
  grid_search:
    verbose: 100  # Verbosity level for hyperparameter search
    cv: 5  # Number of folds for cross-validation
    scoring: 'roc_auc_score'  # Scoring method for grid search. The higher the better
    refit: 'roc_auc_score'  # Scoring method for refitting the best model. The hyperparameter combination with the highest score will be used for the final refit
    error_score: 'raise'  # Default error handling
    return_train_score: False  # Default setting for returning train scores
    n_jobs: -1  # Default number of jobs to run in parallel

  halving_grid_search:
    verbose: 100  # Verbosity level for hyperparameter search
    cv: 5  # Number of folds for cross-validation
    factor: 3  # Reduction factor for the number of candidates to be kept
    resource: 'n_samples'  # Resource used to early stop the search. Can be either 'n_samples' or 'n_iterations'
    max_resources: 'auto'  # Maximum number of resources to be used
    aggressive_elimination: False  # If true, aggressively eliminate candidates
    scoring: 'roc_auc'  # Scoring method for grid search. The higher the better
    refit: 'roc_auc'  # Scoring method for refitting the best model. The hyperparameter combination with the highest score will be used for the final refit
    random_state: null  # Default random state
    #error_score: 'raise'  # Default error handling
    return_train_score: False  # Default setting for returning train scores
    n_jobs: -1  # Default number of jobs to run in parallel. -1 means all processors
  
  random_search:
    verbose: 100  # Verbosity level for hyperparameter search
    cv: 5  # Number of folds for cross-validation
    n_iter: 1000000  # Number of parameter settings sampled for random search
    # Default parameters for RandomizedSearchCV
    scoring: 'roc_auc_score'  # Scoring method for grid search. The higher the better
    refit: 'roc_auc_score'  # Scoring method for refitting the best model. The hyperparameter combination with the highest score will be used for the final refit
    pre_dispatch: '2*n_jobs'  # Default pre-dispatch configuration
    random_state: null  # Default random state
    error_score: 'raise'  # Default error handling
    return_train_score: False  # Default setting for returning train scores
    n_jobs: -1  # Default number of jobs to run in parallel. -1 means all processors

# Hyperparameter Grid (For use with grid or random search)
# structure:
#   model_type:
#     config_name:
#       hyperparameter_name: [hyperparameter_values]
#       ...
hyperparameter_grid:
  random_forest:
    simple:
      n_estimators: [100, 200, 300]
      max_depth: [null, 10, 20, 30]
      min_samples_split: [2, 4, 6]
      min_samples_leaf: [1, 2, 4]
      max_features: ["sqrt", "log2", null]
      bootstrap: [True, False]
      class_weight: [null, "balanced"]
      n_jobs: [-1]
    second:
      n_estimators: [300, 400, 500]
      max_depth: [10, 15, 20, 25, null]
      min_samples_split: [3, 4, 5]
      min_samples_leaf: [2, 3, 4]
      max_features: ["sqrt", "log2"]
      bootstrap: [False]
      class_weight: ["balanced"]
      n_jobs: [-1]
    third:
      n_estimators: [500, 600, 1000]  # Increased upper limit
      max_depth: [10, 40, null]  # Exploring deeper trees and no limit
      min_samples_split: [5, 8]  # Slightly increased values
      min_samples_leaf: [4, 7]  # Slightly increased values
      max_features: ["sqrt", 0.3, 0.5, null]  # Including 'auto' for all features
      bootstrap: [True, False]  # Exploring both options
      class_weight: ["balanced"]
      n_jobs: [-1]
    fourth:
      n_estimators: [1000, 2000, 3000]  # Increased upper limit
      max_depth: [10, 60, 100, null]  # Exploring deeper trees and no limit
      min_samples_split: [5, 10, 15]  # Slightly increased values
      min_samples_leaf: [5, 10, 15]  # Slightly increased values
      max_features: [0.5, 0.7, null]  # Including 'auto' for all features
      bootstrap: [True, False]  # Exploring both options
      class_weight: ["balanced"]
      n_jobs: [-1]